{
  try {
    if (true) {
      throw new CertificateException();
    }
    fail("Should have thrown CertificateException");
  }
 catch (  CertificateException e) {
    assertEquals("Initializer failed : " + e.toString(),"java.security.cert.CertificateException",e.toString());
  }
catch (  Exception e) {
    fail("Unexpected exception during test : " + e);
  }
}
