{
  Class[] exceptions=null;
  Class<? extends IndexOutOfBoundsException> ex=null;
  try {
    Constructor<? extends ConstructorTestHelper> ctor=new ConstructorTestHelper().getClass().getConstructor(new Class[0]);
    exceptions=ctor.getExceptionTypes();
    ex=new IndexOutOfBoundsException().getClass();
  }
 catch (  Exception e) {
    fail("Exception during test : " + e.getMessage());
  }
  assertEquals("Returned exception list of incorrect length",1,exceptions.length);
  assertTrue("Returned incorrect exception",exceptions[0].equals(ex));
}
