{
  try {
    CC.newInstance();
    System.out.println("LocalClass3 succeeded");
  }
 catch (  Exception ex) {
    System.err.println("Got unexpected LocalClass3 failure");
    ex.printStackTrace();
  }
}
