{
  try {
    throwNullPointerException();
  }
 catch (  NullPointerException npe) {
    NullPointerException npe2;
    npe2=new NullPointerException("second throw");
    npe2.initCause(npe);
    throw npe2;
  }
}
