{
  assertEquals("Returned incorrect number of bytes!",s1.length(),si.available());
  simple2.throwExceptionOnNextUse=true;
  assertTrue("IOException on second stream should not affect at this time!",si.available() == s1.length());
  simple1.throwExceptionOnNextUse=true;
  try {
    si.available();
    fail("IOException not thrown!");
  }
 catch (  IOException e) {
  }
}
