{
  SAXParseException exception=new SAXParseException("Oops!",null);
  try {
    parent.warning(exception);
  }
 catch (  SAXException e) {
    throw new RuntimeException("Unexpected exception",e);
  }
  assertEquals(logger.size(),1);
  assertEquals("warning",logger.getMethod());
  assertEquals(new Object[]{exception},logger.getArgs());
}
