{
  super();
  this.exception=exception;
  initCause(exception);
}
