{
  try {
    is.mark(10);
  }
 catch (  Exception e) {
    fail("Unexpected exception: " + e.getMessage());
  }
}
