{
  CertPathValidatorException tE=new CertPathValidatorException();
  assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  for (int i=0; i < msgs.length; i++) {
    tE=new CertPathValidatorException(msgs[i]);
    assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  }
  Throwable cause=null;
  tE=new CertPathValidatorException(cause);
  assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  tE=new CertPathValidatorException(tCause);
  assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  for (int i=0; i < msgs.length; i++) {
    tE=new CertPathValidatorException(msgs[i],tCause);
    assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  }
  tE=new CertPathValidatorException(null,null,null,-1);
  assertEquals("getIndex() must be equals -1",-1,tE.getIndex());
  myCertPath mcp=new myCertPath("X.509","");
  CertPath cp=mcp.get("X.509");
  for (int i=0; i < msgs.length; i++) {
    try {
      tE=new CertPathValidatorException(msgs[i],tCause,cp,-1);
      assertNotNull("getIndex() must not return null",tE.getCertPath());
      assertEquals("getIndex() must return ".concat(cp.toString()),tE.getCertPath(),cp);
    }
 catch (    IndexOutOfBoundsException e) {
      fail("Unexpected IndexOutOfBoundsException was thrown. " + e.getMessage());
    }
  }
}
