{
  try {
    new SecureRandom();
  }
 catch (  Exception e) {
    fail("Constructor threw exception : " + e);
  }
}
