{
  byte[] x={0};
  boolean thrown=false;
  try {
    Array.setByte(x,0,(byte)1);
  }
 catch (  Exception e) {
    fail("Exception during get test : " + e.getMessage());
  }
  assertEquals("Get returned incorrect value",1,Array.getByte(x,0));
  try {
    Array.setByte(new Object(),0,(byte)9);
  }
 catch (  IllegalArgumentException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Passing non-array failed to throw exception");
  }
  thrown=false;
  try {
    Array.setByte(x,4,(byte)9);
  }
 catch (  ArrayIndexOutOfBoundsException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Invalid index failed to throw exception");
  }
  thrown=false;
  try {
    Array.setByte(null,0,(byte)0);
  }
 catch (  NullPointerException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Null argument failed to throw NPE");
  }
}
