{
  NullPointerException npe=new NullPointerException();
  Throwable thr=new Throwable(npe);
  assertEquals("Returned cause is incorrect.",npe,thr.getCause());
  thr=new Throwable((Throwable)null);
  assertNull("The cause is not null.",thr.getCause());
}
