{
  try {
    is.close();
  }
 catch (  Exception e) {
    fail("Unexpected exception: " + e.getMessage());
  }
}
